# Generated by Django 2.1.7 on 2019-04-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190428_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
